# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /var/tmp/persistent/Development/shumlib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /var/tmp/persistent/Development/shumlib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /var/tmp/persistent/Development/shumlib/CMakeFiles /var/tmp/persistent/Development/shumlib//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /var/tmp/persistent/Development/shumlib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named shumlib

# Build rule for target.
shumlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shumlib
.PHONY : shumlib

# fast build rule for target.
shumlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/build
.PHONY : shumlib/fast

common/src/shumlib_version.o: common/src/shumlib_version.c.o
.PHONY : common/src/shumlib_version.o

# target to build an object file
common/src/shumlib_version.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/common/src/shumlib_version.c.o
.PHONY : common/src/shumlib_version.c.o

common/src/shumlib_version.i: common/src/shumlib_version.c.i
.PHONY : common/src/shumlib_version.i

# target to preprocess a source file
common/src/shumlib_version.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/common/src/shumlib_version.c.i
.PHONY : common/src/shumlib_version.c.i

common/src/shumlib_version.s: common/src/shumlib_version.c.s
.PHONY : common/src/shumlib_version.s

# target to generate assembly for a file
common/src/shumlib_version.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/common/src/shumlib_version.c.s
.PHONY : common/src/shumlib_version.c.s

f_shum_string_conv_version_mod.o: f_shum_string_conv_version_mod.f90.o
.PHONY : f_shum_string_conv_version_mod.o

# target to build an object file
f_shum_string_conv_version_mod.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/f_shum_string_conv_version_mod.f90.o
.PHONY : f_shum_string_conv_version_mod.f90.o

f_shum_string_conv_version_mod.i: f_shum_string_conv_version_mod.f90.i
.PHONY : f_shum_string_conv_version_mod.i

# target to preprocess a source file
f_shum_string_conv_version_mod.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/f_shum_string_conv_version_mod.f90.i
.PHONY : f_shum_string_conv_version_mod.f90.i

f_shum_string_conv_version_mod.s: f_shum_string_conv_version_mod.f90.s
.PHONY : f_shum_string_conv_version_mod.s

# target to generate assembly for a file
f_shum_string_conv_version_mod.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/f_shum_string_conv_version_mod.f90.s
.PHONY : f_shum_string_conv_version_mod.f90.s

shum_string_conv/src/f_shum_string_conv.o: shum_string_conv/src/f_shum_string_conv.f90.o
.PHONY : shum_string_conv/src/f_shum_string_conv.o

# target to build an object file
shum_string_conv/src/f_shum_string_conv.f90.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/shum_string_conv/src/f_shum_string_conv.f90.o
.PHONY : shum_string_conv/src/f_shum_string_conv.f90.o

shum_string_conv/src/f_shum_string_conv.i: shum_string_conv/src/f_shum_string_conv.f90.i
.PHONY : shum_string_conv/src/f_shum_string_conv.i

# target to preprocess a source file
shum_string_conv/src/f_shum_string_conv.f90.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/shum_string_conv/src/f_shum_string_conv.f90.i
.PHONY : shum_string_conv/src/f_shum_string_conv.f90.i

shum_string_conv/src/f_shum_string_conv.s: shum_string_conv/src/f_shum_string_conv.f90.s
.PHONY : shum_string_conv/src/f_shum_string_conv.s

# target to generate assembly for a file
shum_string_conv/src/f_shum_string_conv.f90.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shumlib.dir/build.make CMakeFiles/shumlib.dir/shum_string_conv/src/f_shum_string_conv.f90.s
.PHONY : shum_string_conv/src/f_shum_string_conv.f90.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shumlib"
	@echo "... common/src/shumlib_version.o"
	@echo "... common/src/shumlib_version.i"
	@echo "... common/src/shumlib_version.s"
	@echo "... f_shum_string_conv_version_mod.o"
	@echo "... f_shum_string_conv_version_mod.i"
	@echo "... f_shum_string_conv_version_mod.s"
	@echo "... shum_string_conv/src/f_shum_string_conv.o"
	@echo "... shum_string_conv/src/f_shum_string_conv.i"
	@echo "... shum_string_conv/src/f_shum_string_conv.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

